# Generated by Django 2.2.1 on 2019-05-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='major_system',
            new_name='major_system_affected',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='other_system',
            new_name='other_system_affected',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='person_responsible',
            new_name='person_responsible_to_close',
        ),
    ]
