# Generated by Django 2.2.1 on 2019-05-24 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0006_auto_20190524_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='action_required_to_close',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='person_responsible_to_close',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='process',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reputation_consequence',
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(help_text='Description, process, activity, persona responsible to close this incident etc...'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField()),
                ('complaint_received_from', models.CharField(choices=[('Customer', 'Customer'), ('Broker', 'Broker'), ('Licensee', 'Licensee'), ('General Public', 'General Public'), ('Other', 'Other')], max_length=20)),
                ('relevant_customer_number', models.CharField(max_length=20)),
                ('broker_business_name', models.CharField(max_length=100)),
                ('representative_name', models.CharField(max_length=100)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('risk_factor', models.CharField(choices=[('Inappropriate application of Credit Risk Policy', 'Inappropriate application of Credit Risk Policy'), ('Credit concentration risk – portfolio credit concentration / aggregation ', 'Credit concentration risk – portfolio credit concentration / aggregation '), ('Strategic plan risk', 'Strategic plan risk'), ('Market risk – Interest Rate Risk in the Banking Book (IRRBB)', 'Market risk – Interest Rate Risk in the Banking Book (IRRBB)'), ('Minimum Liquid Holdings Requirement', 'Minimum Liquid Holdings Requirement'), ('Outsourcing Risk – Mortgage Brokers', 'Outsourcing Risk – Mortgage Brokers'), ('Breach of the Tax Act', 'Breach of the Tax Act'), ('Fraudulent activity (Internal)', 'Fraudulent activity (Internal)'), ('Fraudulent activity (External)', 'Fraudulent activity (External)'), ('IT Security Risk', 'IT Security Risk'), ('Fit & Proper', 'Fit & Proper'), ('Key Person Risk', 'Key Person Risk'), ('Breach of APRA administered legislation or regulation', 'Breach of APRA administered legislation or regulation'), ('Inappropriate Corporate Governance', 'Inappropriate Corporate Governance'), ('Breach of any Group AFSL conditions', 'Breach of any Group AFSL conditions'), ('Breach of any Group ACL conditions - Banking', 'Breach of any Group ACL conditions - Banking'), ('Breach of any Group ACL conditions - Aggregation', 'Breach of any Group ACL conditions - Aggregation'), ('Breach of the Privacy Act', 'Breach of the Privacy Act'), ('Breach of the AML/CTF Act', 'Breach of the AML/CTF Act'), ('OSH', 'OSH'), ('Liability claim not covered by indemnity insurance', 'Liability claim not covered by indemnity insurance'), ('Loss of records', 'Loss of records'), ('Loss of Point of Representation (POR)', 'Loss of Point of Representation (POR)'), ('Denial of Access to Point of Representation (POR) ', 'Denial of Access to Point of Representation (POR) '), ('Loss of IT Communications', 'Loss of IT Communications'), ('Data Risk', 'Data Risk'), ('Loss of Key Outsourced Dependencies, including Offshoring', 'Loss of Key Outsourced Dependencies, including Offshoring'), ('Account Opening / Fulfilment', 'Account Opening / Fulfilment'), ('Ineffective Risk and Compliance Framework ', 'Ineffective Risk and Compliance Framework '), ('Project Risk', 'Project Risk'), ('Capital Adequacy', 'Capital Adequacy'), ('Breach of NCCP Act', 'Breach of NCCP Act'), ('Complaints including Social Media', 'Complaints including Social Media'), ('Theft including cyber extortion', 'Theft including cyber extortion'), ('Conflict of Interest', 'Conflict of Interest'), ('Competition Risk', 'Competition Risk'), ('Integration Risk', 'Integration Risk'), ('Mortgage management risk', 'Mortgage management risk'), ('Financial Reporting Framework', 'Financial Reporting Framework'), ('Contract Risk', 'Contract Risk'), ('Payment Processing Risk', 'Payment Processing Risk')], max_length=200)),
                ('business_unit', models.CharField(choices=[('Banking', 'Banking'), ('Wholesale', 'Wholesale'), ('Aggregation', 'Aggregation')], max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=200)),
                ('resolution_scheme', models.CharField(choices=[('IDR', 'Internal Dispute Resolution'), ('EDR', 'External Dispute Resolution')], max_length=100)),
                ('category', models.CharField(choices=[('General', 'General'), ('Accounts', 'Accounts'), ('EFT Transactions', 'EFT Transactions'), ('Privacy', 'Privacy'), ('Broker forgery', 'Broker forgery'), ('Broker mis-represented clients', 'Broker mis-represented clients'), ('Broker - bad advice', 'Broker - bad advice'), ('Broker - clawback dispute with client', 'Broker - clawback dispute with client'), ('Loan Hardship/Postponement', 'Loan Hardship/Postponement'), ('Loan Fees, Charges or Interest', 'Loan Fees, Charges or Interest'), ('Product Features', 'Product Features'), ('Joint customer dispute', 'Joint customer dispute'), ('Other', 'Other')], max_length=200)),
                ('category_other', models.CharField(max_length=100)),
                ('litigation_commenced', models.BooleanField()),
                ('description', models.TextField(help_text='Related product, procedure followed, remedial action taken, improvement required,  details of investigation')),
                ('amount_claimed_or_disputed', models.FloatField()),
                ('payment_made_to_complainant', models.FloatField()),
                ('loss_incurred', models.FloatField(help_text='Actual Payout by Group (Loss for Group) to resolve Complaint / Dispute')),
                ('potential_loss', models.FloatField(help_text='Potential Payout by Group (Loss for Group) to resolve Complaint / Dispute')),
                ('closed_date', models.DateTimeField(null=True)),
                ('pursued_with_Ombudsmen', models.BooleanField()),
                ('external_dispute_resolution_details', models.TextField()),
                ('root_cause', models.CharField(choices=[('ATM Error', 'ATM Error'), ('Broker difficult to contact', 'Broker difficult to contact'), ('Core Banking System Error', 'Core Banking System Error'), ('Cyber Fraud', 'Cyber Fraud'), ('Delays due to broker', 'Delays due to broker'), ('Delays due to lender', 'Delays due to lender'), ('Disclosure docs not issued', 'Disclosure docs not issued'), ('Financial Fraud - Vigil', 'Financial Fraud - Vigil'), ('Fraud by Customer', 'Fraud by Customer'), ('Fraud by staff', 'Fraud by staff'), ('Hardware Issue', 'Hardware Issue'), ('Inadequate project governance', 'Inadequate project governance'), ('Incorrect assessment', 'Incorrect assessment'), ('Incorrect/inadequate advice', 'Incorrect/inadequate advice'), ('Incorrect/inadequate cost disclosure', 'Incorrect/inadequate cost disclosure'), ('Incorrect/inadequate product information', 'Incorrect/inadequate product information'), ('Incorrect/process disclosure', 'Incorrect/process disclosure'), ('Lack of staff training', 'Lack of staff training'), ('Loan Hardship/Postponement', 'Loan Hardship/Postponement'), ('Manual processing error', 'Manual processing error'), ('Misunderstanding of legislation', 'Misunderstanding of legislation'), ('Outsourced Activity', 'Outsourced Activity'), ('Paywave - stolen card or dispute', 'Paywave - stolen card or dispute'), ('Policies not followed', 'Policies not followed'), ('Software controls', 'Software controls'), ('Not Applicable', 'Not Applicable')], max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
                ('person_handling_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_complaints', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
