# Generated by Django 2.2.1 on 2019-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20190524_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='litigation_commenced',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pursued_with_Ombudsmen',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
