# Generated by Django 2.2.1 on 2019-05-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_question_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hindsight',
            name='submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewed',
            field=models.CharField(choices=[('', '---------'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not Applicable')], max_length=50),
        ),
    ]
