# Generated by Django 2.2.1 on 2019-05-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20190525_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='monetary_impact',
            new_name='loss_incurred',
        ),
    ]
