# Generated by Django 2.2.1 on 2019-05-25 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_auto_20190525_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='amount_claimed_or_disputed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='loss_incurred',
            field=models.FloatField(help_text='Actual Payout by Group (Loss for Group) to resolve', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='payment_made_to_complainant',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='potential_loss',
            field=models.FloatField(help_text='Potential Payout by Group (Loss for Group) to resolve', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='transaction_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='loss_incurred',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
