# Generated by Django 2.2.1 on 2019-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20190525_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_regulator_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='expected_resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='other_system_affected',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='regulator',
            field=models.CharField(blank=True, choices=[('APRA', 'APRA'), ('ASIC Responsible Lending', 'ASIC Responsible Lending'), ('Asic Other', 'Asic Other'), ('AUSTRAC', 'AUSTRAC'), ('ASX', 'ASX'), ('Not Applicable', 'Not Applicable')], max_length=200, null=True),
        ),
    ]
