# Generated by Django 2.2.1 on 2019-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20190528_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='consequence',
            field=models.CharField(choices=[('1. Insignificant', '1. Insignificant'), ('2. Minor', '2. Minor'), ('3. Moderate', '3. Moderate'), ('4. Major', '4. Major'), ('5. Catastrophic', '5. Catastrophic')], max_length=200),
        ),
    ]
