# Generated by Django 2.2.1 on 2019-05-29 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20190529_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='action_hour',
            field=models.IntegerField(blank=True, help_text='0 to 24', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='action_minute',
            field=models.IntegerField(blank=True, help_text='0 to 60', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='advice_sender_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='advice_sender_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='advice_sender_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
