# Generated by Django 2.2.1 on 2019-06-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_auto_20190605_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='representative_name',
            new_name='complainant_name',
        ),
    ]
