# Generated by Django 2.2.1 on 2019-06-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_auto_20190605_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='broker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
