# Generated by Django 2.2.1 on 2019-06-05 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_complaint_broker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='potential_loss',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
