# Generated by Django 2.2.1 on 2019-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_incident_potential_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='loss_incurred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
