# Generated by Django 2.2.1 on 2019-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_incident_loss_incurred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='loss_incurred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
