# Generated by Django 2.2.1 on 2019-06-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_auto_20190610_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed', max_length=10),
        ),
    ]
