# Generated by Django 2.2.1 on 2019-06-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_fraud_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='risk_owner',
            field=models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board'), ('Head of Technology & Operations', 'Head of Technology & Operations')], max_length=200),
        ),
    ]
