# Generated by Django 2.2.1 on 2019-06-12 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_auto_20190611_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-discovery_date',)},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('-discovery_date',)},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='loss_incurred',
            field=models.FloatField(help_text='$ Actual Payout by Group (Loss for Group) to resolve', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='potential_loss',
            field=models.FloatField(help_text='$ Potential Payout by Group (Loss for Group) to resolve', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='loss_incurred',
            field=models.FloatField(help_text='$ dollar amount of loss incurred', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='major_system_affected',
            field=models.CharField(choices=[('LoanWorks', 'LoanWorks'), ('Loan Kit', 'Loan Kit'), ('T24', 'T24'), ('Insight', 'Insight'), ('Internet Banking', 'Internet Banking'), ('Phone Banking', 'Phone Banking'), ('Public Facing Website', 'Public Facing Website'), ('Not Applicable', 'Not Applicable')], max_length=160),
        ),
        migrations.AlterField(
            model_name='incident',
            name='potential_loss',
            field=models.FloatField(help_text='$ dollar amount of potential loss', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
