# Generated by Django 2.2.1 on 2019-06-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_auto_20190618_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='risk_factor_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='forms.RiskFactor'),
        ),
        migrations.AddField(
            model_name='incident',
            name='risk_factor_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='forms.RiskFactor'),
        ),
    ]
