# Generated by Django 2.2.1 on 2019-06-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0040_auto_20190618_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='risk_factor_m',
            new_name='risk_factor',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='risk_factor_m',
            new_name='risk_factor',
        ),
    ]
