# Generated by Django 2.2.1 on 2019-06-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0041_auto_20190618_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('control_documents', models.CharField(max_length=100)),
                ('operational_loss_event_tier_1_category', models.CharField(help_text='APS115', max_length=50)),
                ('operational_loss_event_tier_2_category', models.CharField(help_text='APS115', max_length=50)),
                ('operational_loss_event_activity', models.CharField(help_text='APS115', max_length=50)),
                ('test_procedure_for_the_quarter', models.TextField()),
                ('control_score_description', models.TextField()),
                ('control_score', models.IntegerField()),
                ('control_effectiveness', models.IntegerField(help_text='%')),
                ('potential_treatment_plans', models.TextField()),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_controls', to='forms.RiskFactor')),
            ],
        ),
    ]
