# Generated by Django 2.2.1 on 2019-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0042_riskcontrol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskfactor',
            old_name='risk_rating',
            new_name='initial_risk_rating',
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='operational_loss_event_activity',
            field=models.CharField(choices=[('Transactions not reported (intentional)', 'Transactions not reported (intentional)'), ('Transaction type (unauthorised)', 'Transaction type (unauthorised)'), ('Mismarking of position (intentional)', 'Mismarking of position (intentional)'), ('Fraud/credit fraud/worthless deposits', 'Fraud/credit fraud/worthless deposits'), ('Theft/extortion/embezzlement/robbery', 'Theft/extortion/embezzlement/robbery'), ('Misappropriation of assets', 'Misappropriation of assets'), ('Malicious destruction of assets', 'Malicious destruction of assets'), ('Forgery', 'Forgery'), ('Cheque kiting', 'Cheque kiting'), ('Smuggling', 'Smuggling'), ('Account take-over/impersonation/ etc', 'Account take-over/impersonation/ etc'), ('Tax non-compliance/evasion (intentional)', 'Tax non-compliance/evasion (intentional)'), ('Bribes/kickbacks', 'Bribes/kickbacks'), ('Insider trading (not on ADI’s account)', 'Insider trading (not on ADI’s account)'), ('Theft/robbery', 'Theft/robbery'), ('Forgery', 'Forgery'), ('Cheque kiting', 'Cheque kiting'), ('Hacking damage', 'Hacking damage'), ('Theft of information (with monetary loss)', 'Theft of information (with monetary loss)'), ('Compensation/ benefit/ termination issues', 'Compensation/ benefit/ termination issues'), ('Organised labour activity', 'Organised labour activity'), ('General liability (slip and fall/ etc)', 'General liability (slip and fall/ etc)'), ('Employee health and safety rules events', 'Employee health and safety rules events'), ('Workers’ compensation', 'Workers’ compensation'), ('All discrimination types', 'All discrimination types'), ('Fiduciary breaches/guideline violations', 'Fiduciary breaches/guideline violations'), ('Suitability/disclosure issues (e. g. know your client requirements)', 'Suitability/disclosure issues (e. g. know your client requirements)'), ('Retail customer disclosure violations', 'Retail customer disclosure violations'), ('Breach of privacy', 'Breach of privacy'), ('Aggressive sales', 'Aggressive sales'), ('Account churning', 'Account churning'), ('Misuse of confidential information', 'Misuse of confidential information'), ('Lender liability', 'Lender liability'), ('Antitrust', 'Antitrust'), ('Improper trade/market practices', 'Improper trade/market practices'), ('Market manipulation', 'Market manipulation'), ('Insider trading (on the ADI’s account)', 'Insider trading (on the ADI’s account)'), ('Unlicensed activity', 'Unlicensed activity'), ('Money laundering', 'Money laundering'), ('Product defects (unauthorised/ etc)', 'Product defects (unauthorised/ etc)'), ('Model errors', 'Model errors'), ('Failure to investigate client per guidelines', 'Failure to investigate client per guidelines'), ('Exceeding client exposure limits', 'Exceeding client exposure limits'), ('Disputes over performance of advisory activities', 'Disputes over performance of advisory activities'), ('Natural disaster losses', 'Natural disaster losses'), ('Human losses from external sources (e.g.terrorism or vandalism)', 'Human losses from external sources (e.g.terrorism or vandalism)'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Telecommunications', 'Telecommunications'), ('Utility outage/disruptions', 'Utility outage/disruptions'), ('Miscommunication', 'Miscommunication'), ('Data entry/ maintenance or loading error', 'Data entry/ maintenance or loading error'), ('Missed deadline or responsibility', 'Missed deadline or responsibility'), ('Model/system mis-operation', 'Model/system mis-operation'), ('Accounting error/entity attribution error', 'Accounting error/entity attribution error'), ('Other task mis-performance', 'Other task mis-performance'), ('Delivery failure', 'Delivery failure'), ('Collateral management failure', 'Collateral management failure'), ('Reference data maintenance', 'Reference data maintenance'), ('Failed mandatory reporting obligation', 'Failed mandatory reporting obligation'), ('Inaccurate external report (loss incurred)', 'Inaccurate external report (loss incurred)'), ('Client permissions/disclaimers missing', 'Client permissions/disclaimers missing'), ('Legal documents missing/incomplete', 'Legal documents missing/incomplete'), ('Unapproved access given to accounts', 'Unapproved access given to accounts'), ('Incorrect client records (loss incurred)', 'Incorrect client records (loss incurred)'), ('Negligent loss or damage of client assets', 'Negligent loss or damage of client assets'), ('Non-client counterparty mis-performance', 'Non-client counterparty mis-performance'), ('Miscellaneous non-client counterparty disputes', 'Miscellaneous non-client counterparty disputes'), ('Outsourcing', 'Outsourcing'), ('Vendor disputes', 'Vendor disputes')], help_text='APS115', max_length=100),
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='operational_loss_event_tier_1_category',
            field=models.CharField(choices=[('Internal fraud', 'Internal fraud'), ('External fraud', 'External fraud'), ('Employment practices and workplace safety', 'Employment practices and workplace safety'), ('Clients/ products and business practices', 'Clients/ products and business practices'), ('Damage to physical assets', 'Damage to physical assets'), ('Business disruption', 'Business disruption'), ('Execution/ delivery and process management', 'Execution/ delivery and process management')], help_text='APS115', max_length=100),
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='operational_loss_event_tier_2_category',
            field=models.CharField(choices=[('Unauthorised activity', 'Unauthorised activity'), ('Theft and fraud', 'Theft and fraud'), ('Theft and fraud', 'Theft and fraud'), ('Systems security', 'Systems security'), ('Employee relations', 'Employee relations'), ('Safe environment', 'Safe environment'), ('Diversity and discrimination', 'Diversity and discrimination'), ('Suitability/ disclosure and fiduciary', 'Suitability/ disclosure and fiduciary'), ('Improper business or market practices', 'Improper business or market practices'), ('Product flaws', 'Product flaws'), ('Selection/ sponsorship and exposure', 'Selection/ sponsorship and exposure'), ('Advisory activities', 'Advisory activities'), ('Disasters and other events', 'Disasters and other events'), ('Systems', 'Systems'), ('Transaction capture/ execution and maintenance', 'Transaction capture/ execution and maintenance'), ('Monitoring and reporting', 'Monitoring and reporting'), ('Customer intake and documentation', 'Customer intake and documentation'), ('Customer/client account management', 'Customer/client account management'), ('Trade counterparties', 'Trade counterparties'), ('Vendors and suppliers', 'Vendors and suppliers')], help_text='APS115', max_length=100),
        ),
    ]
