# Generated by Django 2.2.1 on 2019-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0043_auto_20190619_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskfactor',
            old_name='likelihood',
            new_name='initial_likelihood',
        ),
        migrations.AddField(
            model_name='riskfactor',
            name='control_effectiveness',
            field=models.IntegerField(default=0),
        ),
    ]
