# Generated by Django 2.2.1 on 2019-06-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0047_auto_20190619_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfactor',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='initial_risk_rating',
            field=models.CharField(blank=True, choices=[('1. LOW', '1. LOW'), ('2. MODERATE', '2. MODERATE'), ('3. HIGH', '3. HIGH'), ('4. EXTREME', '4. EXTREME'), ('5. NEW', '5. NEW')], max_length=100),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='previous_residual_risk_rating',
            field=models.CharField(blank=True, choices=[('1. LOW', '1. LOW'), ('2. MODERATE', '2. MODERATE'), ('3. HIGH', '3. HIGH'), ('4. EXTREME', '4. EXTREME'), ('5. NEW', '5. NEW')], max_length=100),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='reason_for_change',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='residual_likelihood',
            field=models.CharField(blank=True, choices=[('1. RARE', '1. RARE'), ('2. UNLIKELY', '2. UNLIKELY'), ('3. POSSIBLE', '3. POSSIBLE'), ('4. LIKELY', '4. LIKELY'), ('5. ALMOST CERTAIN', '5. ALMOST CERTAIN')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='residual_risk_rating',
            field=models.CharField(blank=True, choices=[('1. LOW', '1. LOW'), ('2. MODERATE', '2. MODERATE'), ('3. HIGH', '3. HIGH'), ('4. EXTREME', '4. EXTREME'), ('5. NEW', '5. NEW')], max_length=100),
        ),
    ]
