# Generated by Django 2.2.1 on 2019-06-20 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0049_auto_20190620_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='fraud_type',
            field=models.CharField(choices=[('Romance Scam', 'Romance Scam'), ('Remote Software Hack', 'Remote Software Hack'), ('Porting', 'Porting'), ('Phishing', 'Phishing'), ('Money Mule', 'Money Mule'), ('Malware', 'Malware'), ('Invoice Fraud', 'Invoice Fraud'), ('Investment Scam', 'Investment Scam'), ("ID T'over", "ID T'over"), ('Fraud Bank Transfer', 'Fraud Bank Transfer'), ('Email Hack', 'Email Hack'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraud',
            name='never_recovered_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fraud',
            name='recovered_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fraud',
            name='unrecoverable_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
