# Generated by Django 2.2.1 on 2019-06-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0051_auto_20190621_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hindsight',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='hindsight',
            name='borrower_name',
            field=models.CharField(default='TEST', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hindsight',
            name='loan_approved_by',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='TEST', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hindsight',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
