# Generated by Django 2.2.1 on 2019-06-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0052_auto_20190621_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hindsight',
            old_name='submitted',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='hindsight',
            old_name='submitted_date',
            new_name='completion_date',
        ),
    ]
