# Generated by Django 2.2.1 on 2019-06-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0054_auto_20190621_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hindsight',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hindsight',
            name='loan_approved_by',
            field=models.CharField(choices=[('Simon Lyons', 'Simon Lyons'), ('Allan Savins', 'Allan Savins'), ('Mark Seaman', 'Mark Seaman'), ('Nicole Kata', 'Nicole Kata'), ('Malcolm Cowell', 'Malcolm Cowell'), ('Gloria Mudge', 'Gloria Mudge'), ('Philip Morros', 'Philip Morros'), ('Mark Josephs', 'Mark Josephs'), ('Tim Mackeen', 'Tim Mackeen'), ('Jinesh Patel', 'Jinesh Patel'), ('John Dickinson', 'John Dickinson'), ('Taylor Cray ', 'Taylor Cray '), ('Rachel Meakes', 'Rachel Meakes'), ('Kean Burke', 'Kean Burke'), ('Paul Hay', 'Paul Hay'), ('Ben Shirvani', 'Ben Shirvani')], max_length=50),
        ),
    ]
