# Generated by Django 2.2.1 on 2019-06-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0055_auto_20190624_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskfactor',
            old_name='previous_residual_risk_rating_date',
            new_name='residual_risk_rating_change_date',
        ),
    ]
