# Generated by Django 2.2.1 on 2019-06-26 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0056_auto_20190624_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactorDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('residual_risk_rating', models.CharField(blank=True, choices=[('1. LOW', '1. LOW'), ('2. MODERATE', '2. MODERATE'), ('3. HIGH', '3. HIGH'), ('4. EXTREME', '4. EXTREME'), ('5. NEW', '5. NEW')], max_length=100, null=True)),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='forms.RiskFactor')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_risk_factor_deltas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
