# Generated by Django 2.2.1 on 2019-06-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0057_riskfactordelta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfactor',
            name='previous_residual_risk_rating',
        ),
        migrations.RemoveField(
            model_name='riskfactor',
            name='reason_for_change',
        ),
        migrations.RemoveField(
            model_name='riskfactor',
            name='residual_risk_rating_change_date',
        ),
        migrations.AddField(
            model_name='riskfactordelta',
            name='reason_for_change',
            field=models.TextField(blank=True),
        ),
    ]
