# Generated by Django 2.2.1 on 2019-06-10 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completiondate',
            name='submitter',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_completion_dates', to=settings.AUTH_USER_MODEL),
        ),
    ]
