# Generated by Django 2.2.1 on 2019-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0002_completiondate_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='completiondate',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
