# Generated by Django 2.2.1 on 2019-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0003_completiondate_completion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completiondate',
            options={'ordering': ['-completion_date']},
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=20),
        ),
    ]
