# Generated by Django 2.2.1 on 2019-06-11 03:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance_schedule', '0004_auto_20190610_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('regulators', models.CharField(max_length=50)),
                ('regulatory_guide', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.IntegerField(help_text='0 to 24', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ON SCHEDULE', 'ON SCHEDULE'), ('OVERDUE', 'OVERDUE'), ('AHEAD OF SCHEDULE', 'AHEAD OF SCHEDULE')], max_length=50)),
                ('responsible', models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board'), ('Head of Technology & Operations', 'Head of Technology & Operations')], max_length=200)),
                ('reviewer', models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board'), ('Head of Technology & Operations', 'Head of Technology & Operations')], max_length=200)),
                ('approval_body', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='responsible',
            field=models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board'), ('Head of Technology & Operations', 'Head of Technology & Operations')], max_length=200),
        ),
        migrations.CreateModel(
            name='ReviewDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(null=True)),
                ('policy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_dates', to='compliance_schedule.PolicyItem')),
                ('submitter', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='policy_reviewed_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
