# Generated by Django 2.2.1 on 2019-06-18 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0010_auto_20190612_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completiondate',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_completion_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policyitem',
            name='responsible',
            field=models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board')], max_length=200),
        ),
        migrations.AlterField(
            model_name='policyitem',
            name='reviewer',
            field=models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board')], max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewdate',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_reviewed_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='regulator',
            field=models.CharField(choices=[('BPAY', 'BPAY'), ('APRA', 'APRA'), ('ASX', 'ASX'), ('ASIC', 'ASIC'), ('AUSTRAC', 'AUSTRAC'), ('BPAY', 'BPAY'), ('WORKSAFE', 'WORKSAFE'), ('ATO', 'ATO'), ('WORKPLACE GENDER EQUALITY AGENCY', 'WORKPLACE GENDER EQUALITY AGENCY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='responsible',
            field=models.CharField(choices=[('Managing Director - GMY', 'Managing Director - GMY'), ('GM Banking & Wholesale', 'GM Banking & Wholesale'), ('GM Aggregation', 'GM Aggregation'), ('Group CFO', 'Group CFO'), ('Banking CFO / Company Sec', 'Banking CFO / Company Sec'), ('Chief Risk Officer', 'Chief Risk Officer'), ('Head of Technology and Operations', 'Head of Technology and Operations'), ('Managing Director - Finsure', 'Managing Director - Finsure'), ('Board', 'Board')], max_length=200),
        ),
    ]
