# Generated by Django 2.2.1 on 2019-06-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0012_auto_20190618_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='regulatory_requirement',
            new_name='compliance_requirement',
        ),
    ]
