# Generated by Django 2.2.1 on 2019-06-07 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateTimeField()),
                ('banking', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wholesale', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('aggregation', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
