# Generated by Django 2.2.1 on 2019-06-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potentialloss',
            old_name='aggregation',
            new_name='Aggregation',
        ),
        migrations.RenameField(
            model_name='potentialloss',
            old_name='banking',
            new_name='Banking',
        ),
        migrations.RenameField(
            model_name='potentialloss',
            old_name='wholesale',
            new_name='Wholesale',
        ),
    ]
