"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
from configparser import RawConfigParser
import os
config = RawConfigParser()
config.read('/opt/settings.ini')


#SECURE_BROWSER_XSS_FILTER = True
#SECURE_CONTENT_TYPE_NOSNIFF = True
#SESSION_COOKIE_SECURE = True

# SECURE_SSL_REDIRECT = True
#CSRF_COOKIE_SECURE=  True
#X_FRAME_OPTIONS = "DENY"

LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL= 'login'
LOGOUT_URL ='logout'
STATIC_ROOT = "/var/www/django2/mysite/mysite/static/"
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(os.path.join(__file__,os.pardir))))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('section','DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

""" Once you move your site to production and
set DEBUG to False, you will have to add your domain/host to
this setting in order to allow it to serve your Django site.
"""
ALLOWED_HOSTS = []


# Application definition
SITE_ID=1
INSTALLED_APPS = [
    'account',
    'taggit',
    'dashboard',
    'forms',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    # for building sitemaps
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'widget_tweaks',
    'rangefilter',
    'compliance_schedule'


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangodb',
        'USER':config.get('section','MYSQL_ACCOUNT'),
        'PASSWORD':config.get('section','MYSQL_PASSWORD'),
        'HOST':'3.105.226.33',
        'PORT':'3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
USE_TZ=True
TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True


#EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
#EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = config.get('section','DJANGO_GMAIL')
EMAIL_HOST_PASSWORD = config.get('section','DJANGO_GMAIL_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
